import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

export async function POST() {
  try {
    const productCount = await db.product.count();
    if (productCount > 0) {
      return NextResponse.json({ message: 'Database already seeded', count: productCount });
    }

    // ==================== CATEGORIES (20) ====================
    const categories = await Promise.all([
      db.category.create({ data: { name: 'Electronics', slug: 'electronics', description: 'Premium tech and gadgets for the modern lifestyle', image: '/products/smartwatch.png', sortOrder: 1 } }),
      db.category.create({ data: { name: 'Fashion', slug: 'fashion', description: 'Curated style essentials for every wardrobe', image: '/products/leather-bag.png', sortOrder: 2 } }),
      db.category.create({ data: { name: 'Home & Living', slug: 'home-living', description: 'Elevate your living space with curated decor', image: '/products/candle.png', sortOrder: 3 } }),
      db.category.create({ data: { name: 'Beauty', slug: 'beauty', description: 'Luxury beauty and wellness essentials', image: '/products/skincare.png', sortOrder: 4 } }),
      db.category.create({ data: { name: 'Accessories', slug: 'accessories', description: 'The perfect finishing touches for any look', image: '/products/analog-watch.png', sortOrder: 5 } }),
      db.category.create({ data: { name: 'Sports & Outdoors', slug: 'sports-outdoors', description: 'Gear for every adventure and fitness goal', image: '/products/running-shoes.png', sortOrder: 6 } }),
      db.category.create({ data: { name: 'Food & Gourmet', slug: 'food-gourmet', description: 'Artisan pantry items and gourmet delights', image: '/products/coffee.png', sortOrder: 7 } }),
      db.category.create({ data: { name: 'Books & Media', slug: 'books-media', description: 'Bestsellers, classics, and everything in between', image: '/products/book.png', sortOrder: 8 } }),
      db.category.create({ data: { name: 'Jewelry', slug: 'jewelry', description: 'Timeless pieces for every occasion', image: '/products/gold-ring.png', sortOrder: 9 } }),
      db.category.create({ data: { name: 'Kitchen & Dining', slug: 'kitchen-dining', description: 'Premium cookware and dining essentials', image: '/products/ceramic-knives.png', sortOrder: 10 } }),
      db.category.create({ data: { name: 'Automotive', slug: 'automotive', description: 'Premium car accessories and essentials', image: '/products/car-mount.png', sortOrder: 11 } }),
      db.category.create({ data: { name: 'Garden & Outdoor', slug: 'garden-outdoor', description: 'Everything for your garden and outdoor space', image: '/products/pruning-tools.png', sortOrder: 12 } }),
      db.category.create({ data: { name: 'Pet Supplies', slug: 'pet-supplies', description: 'Premium care for your furry friends', image: '/products/dog-treats.png', sortOrder: 13 } }),
      db.category.create({ data: { name: 'Office & Stationery', slug: 'office-stationery', description: 'Elevate your workspace with premium supplies', image: '/products/desk-pad.png', sortOrder: 14 } }),
      db.category.create({ data: { name: 'Health & Wellness', slug: 'health-wellness', description: 'Your wellness journey starts here', image: '/products/thermometer.png', sortOrder: 15 } }),
      db.category.create({ data: { name: 'Baby & Kids', slug: 'baby-kids', description: 'Safe, gentle products for the little ones', image: '/products/baby-care.png', sortOrder: 16 } }),
      db.category.create({ data: { name: 'Toys & Games', slug: 'toys-games', description: 'Fun, educational play for all ages', image: '/products/puzzle-toy.png', sortOrder: 17 } }),
      db.category.create({ data: { name: 'Travel & Luggage', slug: 'travel-luggage', description: 'Travel in style with premium luggage', image: '/products/suitcase.png', sortOrder: 18 } }),
      db.category.create({ data: { name: 'Home Improvement', slug: 'home-improvement', description: 'Smart solutions for a better home', image: '/products/led-bulbs.png', sortOrder: 19 } }),
      db.category.create({ data: { name: 'Music & Audio', slug: 'music-audio', description: 'Premium audio equipment and instruments', image: '/products/bluetooth-speaker.png', sortOrder: 20 } }),
    ]);

    const [electronics, fashion, homeLiving, beauty, accessories, sports, foodGourmet, booksMedia, jewelry, kitchen, automotive, garden, petSupplies, office, health, baby, toys, travel, homeImprove, music] = categories;

    // ==================== PRODUCTS (126) ====================
    const products = [
      // --- ELECTRONICS (8) ---
      { name: 'Aura Pro Wireless Headphones', slug: 'aura-pro-wireless-headphones', shortDesc: 'Premium noise-cancelling headphones with 30hr battery', price: 249.99, comparePrice: 299.99, costPrice: 120, images: JSON.stringify(['/products/headphones.png']), categoryId: electronics.id, stock: 45, sku: 'AURA-HP-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ color: 'Matte Black', connectivity: 'Bluetooth 5.3', battery: '30 hours', weight: '250g' }), rating: 4.8, reviewCount: 124, soldCount: 892 },
      { name: 'Meridian Smart Watch', slug: 'meridian-smart-watch', shortDesc: 'Elegant smart watch with leather strap', price: 349.99, comparePrice: 399.99, costPrice: 180, images: JSON.stringify(['/products/smartwatch.png']), categoryId: electronics.id, stock: 30, sku: 'MER-SW-002', isFeatured: true, isNew: true, attributes: JSON.stringify({ color: 'Silver/Brown Leather', display: '1.4" AMOLED', battery: '7 days', water_resistance: '5ATM' }), rating: 4.7, reviewCount: 89, soldCount: 567 },
      { name: 'Nova Portable Speaker', slug: 'nova-portable-speaker', shortDesc: '360° sound, waterproof, 20hr battery', price: 129.99, comparePrice: 159.99, costPrice: 55, images: JSON.stringify(['/products/speaker.png']), categoryId: electronics.id, stock: 60, sku: 'NOVA-SP-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ color: 'Charcoal', battery: '20 hours', waterproof: 'IPX7', weight: '540g' }), rating: 4.6, reviewCount: 67, soldCount: 423 },
      { name: 'Pulse Wireless Earbuds', slug: 'pulse-wireless-earbuds', shortDesc: 'True wireless with active noise cancellation', price: 179.99, comparePrice: 219.99, costPrice: 75, images: JSON.stringify(['/products/earbuds.png']), categoryId: electronics.id, stock: 80, sku: 'PULSE-EB-004', isFeatured: true, isNew: false, attributes: JSON.stringify({ color: 'White', connectivity: 'Bluetooth 5.2', battery: '8 hours', anc: 'Hybrid ANC' }), rating: 4.5, reviewCount: 156, soldCount: 1023 },
      { name: 'Vortex Mechanical Keyboard', slug: 'vortex-mechanical-keyboard', shortDesc: 'Hot-swappable switches, RGB backlight', price: 149.99, comparePrice: 179.99, costPrice: 65, images: JSON.stringify(['/products/keyboard.png']), categoryId: electronics.id, stock: 35, sku: 'VTX-KB-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ switches: 'Hot-swap', layout: '75%', backlight: 'RGB', connectivity: 'USB-C/Bluetooth' }), rating: 4.7, reviewCount: 78, soldCount: 345 },
      { name: 'Apex Gaming Mouse', slug: 'apex-gaming-mouse', shortDesc: 'Ultra-lightweight, 25K DPI sensor', price: 89.99, comparePrice: 109.99, costPrice: 35, images: JSON.stringify(['/products/gaming-mouse.png']), categoryId: electronics.id, stock: 50, sku: 'APEX-GM-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ sensor: '25,600 DPI', weight: '58g', buttons: '8 programmable', switches: 'Optical' }), rating: 4.4, reviewCount: 92, soldCount: 678 },
      { name: 'DashCam Pro 4K', slug: 'dashcam-pro-4k', shortDesc: '4K recording with night vision and GPS', price: 199.99, comparePrice: 249.99, costPrice: 85, images: JSON.stringify(['/products/dash-cam.png']), categoryId: electronics.id, stock: 25, sku: 'DCAM-4K-007', isFeatured: false, isNew: false, attributes: JSON.stringify({ resolution: '4K UHD', night_vision: true, gps: true, screen: '3" IPS' }), rating: 4.3, reviewCount: 54, soldCount: 234 },
      { name: 'Charging Station Pro', slug: 'charging-station-pro', shortDesc: '5-in-1 wireless charging station', price: 79.99, comparePrice: 99.99, costPrice: 30, images: JSON.stringify(['/products/charging-station.png']), categoryId: electronics.id, stock: 40, sku: 'CHG-5IN-008', isFeatured: false, isNew: true, attributes: JSON.stringify({ devices: '5', power: '15W max', compatible: 'Qi/Apple/Samsung', material: 'Aluminum' }), rating: 4.5, reviewCount: 43, soldCount: 312 },

      // --- FASHION (7) ---
      { name: 'Artisan Leather Tote', slug: 'artisan-leather-tote', shortDesc: 'Full-grain leather, handcrafted', price: 289.99, comparePrice: 349.99, costPrice: 120, images: JSON.stringify(['/products/leather-bag.png']), categoryId: fashion.id, stock: 20, sku: 'ART-LT-001', isFeatured: true, isNew: false, attributes: JSON.stringify({ material: 'Full-grain leather', color: 'Cognac', dimensions: '16"x12"x6"' }), rating: 4.9, reviewCount: 87, soldCount: 456 },
      { name: 'Classic White Sneakers', slug: 'classic-white-sneakers', shortDesc: 'Premium leather, timeless design', price: 159.99, comparePrice: 189.99, costPrice: 65, images: JSON.stringify(['/products/sneakers.png']), categoryId: fashion.id, stock: 40, sku: 'CLS-SN-002', isFeatured: true, isNew: true, attributes: JSON.stringify({ material: 'Premium leather', color: 'White', sizes: '6-13', sole: 'Vulcanized rubber' }), rating: 4.7, reviewCount: 134, soldCount: 789 },
      { name: 'Luxury Cashmere Scarf', slug: 'luxury-cashmere-scarf', shortDesc: '100% Mongolian cashmere', price: 199.99, comparePrice: 249.99, costPrice: 80, images: JSON.stringify(['/products/silk-scarf.png']), categoryId: fashion.id, stock: 25, sku: 'LUX-CS-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: '100% Cashmere', size: '200x70cm', care: 'Dry clean only' }), rating: 4.8, reviewCount: 56, soldCount: 234 },
      { name: 'Tailored Linen Shirt', slug: 'tailored-linen-shirt', shortDesc: 'Breathable premium linen, relaxed fit', price: 89.99, comparePrice: 119.99, costPrice: 35, images: JSON.stringify(['/products/wallet.png']), categoryId: fashion.id, stock: 55, sku: 'TLS-LS-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: '100% European Linen', fit: 'Relaxed', colors: 'White/Sand/Sage' }), rating: 4.5, reviewCount: 78, soldCount: 567 },
      { name: 'Running Performance Shoes', slug: 'running-performance-shoes', shortDesc: 'Lightweight, responsive cushioning', price: 179.99, comparePrice: 219.99, costPrice: 75, images: JSON.stringify(['/products/running-shoes.png']), categoryId: fashion.id, stock: 35, sku: 'RUN-PS-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ weight: '245g', cushioning: 'ZoomX foam', drop: '8mm', upper: 'Engineered mesh' }), rating: 4.6, reviewCount: 102, soldCount: 678 },
      { name: 'Premium Denim Jacket', slug: 'premium-denim-jacket', shortDesc: 'Selvedge denim, vintage wash', price: 149.99, comparePrice: 189.99, costPrice: 60, images: JSON.stringify(['/products/messenger-bag.png']), categoryId: fashion.id, stock: 30, sku: 'PRM-DJ-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Selvedge Denim', wash: 'Vintage Medium', fit: 'Regular', buttons: 'Metal shank' }), rating: 4.4, reviewCount: 45, soldCount: 234 },
      { name: 'Silk Blend Evening Dress', slug: 'silk-blend-evening-dress', shortDesc: 'Elegant silk blend, timeless silhouette', price: 329.99, comparePrice: 399.99, costPrice: 140, images: JSON.stringify(['/products/perfume.png']), categoryId: fashion.id, stock: 15, sku: 'SLK-ED-007', isFeatured: true, isNew: true, attributes: JSON.stringify({ material: 'Silk Blend', length: 'Midi', color: 'Midnight Black', lining: 'Satin' }), rating: 4.8, reviewCount: 34, soldCount: 156 },

      // --- HOME & LIVING (8) ---
      { name: 'Artisan Soy Candle Set', slug: 'artisan-soy-candle-set', shortDesc: 'Three-pack of hand-poured soy candles', price: 49.99, comparePrice: 64.99, costPrice: 18, images: JSON.stringify(['/products/candle-set.png']), categoryId: homeLiving.id, stock: 40, sku: 'ART-SC-001', isFeatured: true, isNew: false, attributes: JSON.stringify({ scents: 'Vanilla/Cedar/Lavender', burn_time: '45hrs each', wax: '100% Soy', wick: 'Cotton' }), rating: 4.7, reviewCount: 112, soldCount: 890 },
      { name: 'Handwoven Throw Blanket', slug: 'handwoven-throw-blanket', shortDesc: 'Alpaca wool blend, ultra-soft', price: 129.99, comparePrice: 169.99, costPrice: 50, images: JSON.stringify(['/products/blanket.png']), categoryId: homeLiving.id, stock: 25, sku: 'HWV-TB-002', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Alpaca Wool Blend', size: '130x180cm', weight: '800g', care: 'Dry clean' }), rating: 4.8, reviewCount: 67, soldCount: 345 },
      { name: 'Ceramic Vase Collection', slug: 'ceramic-vase-collection', shortDesc: 'Set of 3 minimalist ceramic vases', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/vase.png']), categoryId: homeLiving.id, stock: 30, sku: 'CRC-VC-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '3', material: 'Stoneware', colors: 'White/Sand/Grey', finish: 'Matte' }), rating: 4.5, reviewCount: 45, soldCount: 234 },
      { name: 'Brass Desk Lamp', slug: 'brass-desk-lamp', shortDesc: 'Adjustable arm, warm LED light', price: 119.99, comparePrice: 149.99, costPrice: 45, images: JSON.stringify(['/products/brass-lamp.png']), categoryId: homeLiving.id, stock: 20, sku: 'BRS-DL-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Brushed Brass', light: 'Warm LED', dimmable: true, height: '45cm' }), rating: 4.6, reviewCount: 38, soldCount: 178 },
      { name: 'Monstera Plant in Pot', slug: 'monstera-plant-in-pot', shortDesc: 'Live plant with ceramic planter', price: 69.99, comparePrice: 89.99, costPrice: 25, images: JSON.stringify(['/products/monstera.png']), categoryId: homeLiving.id, stock: 15, sku: 'MON-PP-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ plant: 'Monstera Deliciosa', pot: 'Ceramic', pot_size: '6 inch', light: 'Indirect bright' }), rating: 4.4, reviewCount: 29, soldCount: 156 },
      { name: 'Decorative Plant Pot Set', slug: 'decorative-plant-pot-set', shortDesc: 'Set of 4 geometric planters', price: 59.99, comparePrice: 79.99, costPrice: 20, images: JSON.stringify(['/products/plant-pot.png']), categoryId: homeLiving.id, stock: 35, sku: 'DEC-PP-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '4', material: 'Ceramic', shapes: 'Geometric', colors: 'Terracotta/Sage/White/Grey' }), rating: 4.5, reviewCount: 41, soldCount: 267 },
      { name: 'Luxury Scented Candle', slug: 'luxury-scented-candle', shortDesc: 'Hand-poured, 60hr burn time', price: 39.99, comparePrice: 49.99, costPrice: 14, images: JSON.stringify(['/products/candle.png']), categoryId: homeLiving.id, stock: 50, sku: 'LUX-SC-007', isFeatured: false, isNew: false, attributes: JSON.stringify({ scent: 'Amber & Sandalwood', burn_time: '60 hours', wax: 'Coconut-Soy blend', weight: '340g' }), rating: 4.6, reviewCount: 89, soldCount: 567 },
      { name: 'Artisan Dinner Plates Set', slug: 'artisan-dinner-plates-set', shortDesc: 'Set of 4 handmade stoneware plates', price: 89.99, comparePrice: 109.99, costPrice: 35, images: JSON.stringify(['/products/dinner-plates.png']), categoryId: homeLiving.id, stock: 20, sku: 'ART-DP-008', isFeatured: false, isNew: true, attributes: JSON.stringify({ pieces: '4', material: 'Stoneware', diameter: '10.5"', finish: 'Reactive Glaze', dishwasher: true }), rating: 4.7, reviewCount: 34, soldCount: 189 },

      // --- BEAUTY (6) ---
      { name: 'Botanical Face Serum', slug: 'botanical-face-serum', shortDesc: 'Hyaluronic acid + Vitamin C complex', price: 59.99, comparePrice: 79.99, costPrice: 18, images: JSON.stringify(['/products/skincare.png']), categoryId: beauty.id, stock: 45, sku: 'BOT-FS-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ volume: '30ml', ingredients: 'Hyaluronic Acid, Vitamin C, Niacinamide', skin_type: 'All', cruelty_free: true }), rating: 4.8, reviewCount: 178, soldCount: 1234 },
      { name: 'Luxury Perfume - Oud Noir', slug: 'luxury-perfume-oud-noir', shortDesc: 'Intense oud, amber, and vanilla', price: 189.99, comparePrice: 249.99, costPrice: 70, images: JSON.stringify(['/products/luxury-perfume.png']), categoryId: beauty.id, stock: 20, sku: 'LUX-PF-002', isFeatured: true, isNew: false, attributes: JSON.stringify({ volume: '100ml', notes: 'Oud/Amber/Vanilla', concentration: 'Eau de Parfum', longevity: '12+ hours' }), rating: 4.9, reviewCount: 89, soldCount: 567 },
      { name: 'Rose Gold Perfume', slug: 'rose-gold-perfume', shortDesc: 'Delicate rose, peony, and musk', price: 149.99, comparePrice: 189.99, costPrice: 55, images: JSON.stringify(['/products/perfume.png']), categoryId: beauty.id, stock: 25, sku: 'RGD-PF-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ volume: '50ml', notes: 'Rose/Peony/Musk', concentration: 'Eau de Parfum', longevity: '8+ hours' }), rating: 4.7, reviewCount: 67, soldCount: 345 },
      { name: 'Organic Essential Oils Set', slug: 'organic-essential-oils-set', shortDesc: '6-pack of pure organic essential oils', price: 44.99, comparePrice: 59.99, costPrice: 15, images: JSON.stringify(['/products/essential-oils.png']), categoryId: beauty.id, stock: 35, sku: 'ORG-EO-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ oils: 'Lavender/Eucalyptus/Tea Tree/Peppermint/Lemon/Orange', volume: '10ml each', purity: '100% Pure', organic: true }), rating: 4.6, reviewCount: 112, soldCount: 789 },
      { name: 'Premium Hair Care Kit', slug: 'premium-hair-care-kit', shortDesc: 'Shampoo, conditioner, and hair mask set', price: 79.99, comparePrice: 99.99, costPrice: 30, images: JSON.stringify(['/products/oil-set.png']), categoryId: beauty.id, stock: 30, sku: 'PRM-HC-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '3', size: '250ml each', hair_type: 'All', sulfate_free: true }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Jade Face Roller & Gua Sha', slug: 'jade-face-roller-gua-sha', shortDesc: 'Natural jade stone, duo set', price: 29.99, comparePrice: 39.99, costPrice: 8, images: JSON.stringify(['/products/skincare.png']), categoryId: beauty.id, stock: 60, sku: 'JAD-FR-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Natural Jade', pieces: '2 (Roller + Gua Sha)', benefits: 'Depuffing/Firming', care: 'Wipe clean' }), rating: 4.4, reviewCount: 89, soldCount: 567 },

      // --- ACCESSORIES (6) ---
      { name: 'Analog Watch - Heritage', slug: 'analog-watch-heritage', shortDesc: 'Swiss movement, sapphire crystal', price: 299.99, comparePrice: 379.99, costPrice: 130, images: JSON.stringify(['/products/analog-watch.png']), categoryId: accessories.id, stock: 15, sku: 'ANA-WH-001', isFeatured: true, isNew: false, attributes: JSON.stringify({ movement: 'Swiss Quartz', crystal: 'Sapphire', case: 'Stainless Steel 40mm', strap: 'Italian Leather' }), rating: 4.8, reviewCount: 67, soldCount: 234 },
      { name: 'Designer Sunglasses', slug: 'designer-sunglasses', shortDesc: 'Polarized lenses, titanium frame', price: 219.99, comparePrice: 279.99, costPrice: 85, images: JSON.stringify(['/products/sunglasses.png']), categoryId: accessories.id, stock: 25, sku: 'DSG-SG-002', isFeatured: false, isNew: true, attributes: JSON.stringify({ lens: 'Polarized', frame: 'Titanium', uv_protection: 'UV400', weight: '22g' }), rating: 4.6, reviewCount: 45, soldCount: 234 },
      { name: 'Premium Leather Wallet', slug: 'premium-leather-wallet', shortDesc: 'Full-grain leather, RFID blocking', price: 89.99, comparePrice: 109.99, costPrice: 35, images: JSON.stringify(['/products/wallet.png']), categoryId: accessories.id, stock: 40, sku: 'PRM-LW-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Full-grain Leather', rfid: true, slots: '8 card + 2 bill', color: 'Dark Brown' }), rating: 4.7, reviewCount: 134, soldCount: 890 },
      { name: 'Messenger Bag - Canvas', slug: 'messenger-bag-canvas', shortDesc: 'Waxed canvas, leather trim', price: 149.99, comparePrice: 189.99, costPrice: 55, images: JSON.stringify(['/products/messenger-bag.png']), categoryId: accessories.id, stock: 30, sku: 'MSG-BC-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Waxed Canvas + Leather', laptop: 'Fits 15"', pockets: '6', strap: 'Adjustable' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Diamond Stud Earrings', slug: 'diamond-stud-earrings', shortDesc: '0.5ct total, 14K white gold', price: 399.99, comparePrice: 499.99, costPrice: 180, images: JSON.stringify(['/products/diamond-earrings.png']), categoryId: accessories.id, stock: 10, sku: 'DMD-SE-005', isFeatured: true, isNew: true, attributes: JSON.stringify({ carat: '0.5ct total', metal: '14K White Gold', clarity: 'VS2', setting: '4-Prong' }), rating: 4.9, reviewCount: 23, soldCount: 89 },
      { name: 'Charm Bracelet', slug: 'charm-bracelet', shortDesc: 'Sterling silver with 5 charms', price: 69.99, comparePrice: 89.99, costPrice: 25, images: JSON.stringify(['/products/charm-bracelet.png']), categoryId: accessories.id, stock: 35, sku: 'CHM-BR-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ metal: 'Sterling Silver', charms: '5', length: '7.5"', plating: 'Rhodium' }), rating: 4.4, reviewCount: 45, soldCount: 234 },

      // --- SPORTS & OUTDOORS (7) ---
      { name: 'Pro Yoga Mat', slug: 'pro-yoga-mat', shortDesc: 'Extra thick, non-slip, eco-friendly', price: 79.99, comparePrice: 99.99, costPrice: 30, images: JSON.stringify(['/products/yoga-mat.png']), categoryId: sports.id, stock: 40, sku: 'PRO-YM-001', isFeatured: true, isNew: false, attributes: JSON.stringify({ thickness: '6mm', material: 'Natural Rubber + TPE', size: '183x68cm', eco: true }), rating: 4.7, reviewCount: 98, soldCount: 567 },
      { name: 'Insulated Water Bottle', slug: 'insulated-water-bottle', shortDesc: 'Triple-wall vacuum, 24hr cold/12hr hot', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/steel-bottle.png']), categoryId: sports.id, stock: 60, sku: 'INS-WB-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ capacity: '750ml', material: 'Stainless Steel', insulation: 'Triple-wall vacuum', bpa_free: true }), rating: 4.6, reviewCount: 156, soldCount: 890 },
      { name: 'Yoga Block Set', slug: 'yoga-block-set', shortDesc: 'EVA foam, 2-pack with strap', price: 24.99, comparePrice: 34.99, costPrice: 8, images: JSON.stringify(['/products/yoga-block.png']), categoryId: sports.id, stock: 50, sku: 'YGA-BS-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'EVA Foam', pieces: '2 blocks + strap', size: '9"x6"x4"', weight: '200g each' }), rating: 4.5, reviewCount: 67, soldCount: 456 },
      { name: 'Resistance Band Set', slug: 'resistance-band-set', shortDesc: '5 bands with handles and door anchor', price: 39.99, comparePrice: 54.99, costPrice: 12, images: JSON.stringify(['/products/green-mat.png']), categoryId: sports.id, stock: 45, sku: 'RES-RB-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ bands: '5 (10-50lbs)', accessories: 'Handles + Door Anchor + Ankle Straps', material: 'Natural Latex', carry_bag: true }), rating: 4.4, reviewCount: 89, soldCount: 567 },
      { name: 'Running Hydration Belt', slug: 'running-hydration-belt', shortDesc: 'Lightweight with 2 water bottles', price: 29.99, comparePrice: 39.99, costPrice: 10, images: JSON.stringify(['/products/water-bottle.png']), categoryId: sports.id, stock: 35, sku: 'RUN-HB-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ bottles: '2 x 200ml', pockets: '3 (zip)', reflective: true, adjustable: true }), rating: 4.3, reviewCount: 34, soldCount: 234 },
      { name: 'Foam Roller Pro', slug: 'foam-roller-pro', shortDesc: 'Deep tissue massage, high-density', price: 44.99, comparePrice: 59.99, costPrice: 15, images: JSON.stringify(['/products/yoga-mat.png']), categoryId: sports.id, stock: 30, sku: 'FMR-PR-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'EVA Foam', texture: 'Multi-zone', length: '45cm', diameter: '15cm' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Jump Rope Speed Pro', slug: 'jump-rope-speed-pro', shortDesc: 'Adjustable steel cable, ball bearings', price: 19.99, comparePrice: 29.99, costPrice: 5, images: JSON.stringify(['/products/running-shoes.png']), categoryId: sports.id, stock: 70, sku: 'JRP-SP-007', isFeatured: false, isNew: false, attributes: JSON.stringify({ cable: 'Steel', bearings: 'Ball bearing', adjustable: '8-10ft', grip: 'EVA foam' }), rating: 4.4, reviewCount: 78, soldCount: 456 },

      // --- FOOD & GOURMET (6) ---
      { name: 'Single Origin Coffee Beans', slug: 'single-origin-coffee-beans', shortDesc: 'Ethiopian Yirgacheffe, light roast', price: 24.99, comparePrice: 32.99, costPrice: 8, images: JSON.stringify(['/products/coffee.png']), categoryId: foodGourmet.id, stock: 80, sku: 'SOR-CB-001', isFeatured: true, isNew: false, attributes: JSON.stringify({ origin: 'Ethiopia Yirgacheffe', roast: 'Light', weight: '340g', process: 'Washed' }), rating: 4.8, reviewCount: 189, soldCount: 1234 },
      { name: 'Extra Virgin Olive Oil', slug: 'extra-virgin-olive-oil', shortDesc: 'Cold-pressed, Italian estate', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/olive-oil.png']), categoryId: foodGourmet.id, stock: 40, sku: 'EVO-OO-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ origin: 'Italy Puglia', press: 'Cold-pressed', volume: '750ml', acidity: '<0.3%' }), rating: 4.7, reviewCount: 67, soldCount: 456 },
      { name: 'Artisan Chocolate Collection', slug: 'artisan-chocolate-collection', shortDesc: '12-piece dark chocolate truffle box', price: 44.99, comparePrice: 54.99, costPrice: 16, images: JSON.stringify(['/products/chocolate.png']), categoryId: foodGourmet.id, stock: 25, sku: 'ART-CC-003', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '12', cocoa: '70% Dark', fillings: 'Caramel/Sea Salt/Raspberry/Mint', box: 'Gift box' }), rating: 4.9, reviewCount: 78, soldCount: 567 },
      { name: 'Premium Wine Glasses Set', slug: 'premium-wine-glasses-set', shortDesc: 'Crystal stemware, set of 6', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/wine-glasses.png']), categoryId: foodGourmet.id, stock: 20, sku: 'PRM-WG-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '6', material: 'Crystal', capacity: '450ml', dishwasher: true }), rating: 4.6, reviewCount: 45, soldCount: 234 },
      { name: 'Gourmet Spice Collection', slug: 'gourmet-spice-collection', shortDesc: '12 organic spices in glass jars', price: 49.99, comparePrice: 64.99, costPrice: 16, images: JSON.stringify(['/products/essential-oils.png']), categoryId: foodGourmet.id, stock: 30, sku: 'GOU-SC-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ spices: '12', size: '60g each', organic: true, jars: 'Glass with grinder' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Raw Honey Set', slug: 'raw-honey-set', shortDesc: '3 varieties of unfiltered raw honey', price: 39.99, comparePrice: 49.99, costPrice: 14, images: JSON.stringify(['/products/olive-oil.png']), categoryId: foodGourmet.id, stock: 35, sku: 'RAW-HS-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ varieties: 'Wildflower/Manuka/Acacia', size: '250g each', raw: true, unfiltered: true }), rating: 4.7, reviewCount: 45, soldCount: 234 },

      // --- BOOKS & MEDIA (6) ---
      { name: 'The Art of Minimalism', slug: 'the-art-of-minimalism', shortDesc: 'A guide to intentional living', price: 24.99, comparePrice: 32.99, costPrice: 8, images: JSON.stringify(['/products/book.png']), categoryId: booksMedia.id, stock: 60, sku: 'AOM-BK-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ format: 'Hardcover', pages: '288', author: 'Various', isbn: '978-1-234567-89-0' }), rating: 4.6, reviewCount: 89, soldCount: 567 },
      { name: 'Premium Leather Journal', slug: 'premium-leather-journal', shortDesc: 'Hand-stitched, 240 pages', price: 39.99, comparePrice: 49.99, costPrice: 14, images: JSON.stringify(['/products/journal.png']), categoryId: booksMedia.id, stock: 40, sku: 'PRM-LJ-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Genuine Leather', pages: '240 (acid-free)', size: 'A5', binding: 'Hand-stitched' }), rating: 4.7, reviewCount: 67, soldCount: 456 },
      { name: 'Classic Board Game Collection', slug: 'classic-board-game-collection', shortDesc: 'Premium wooden board game set', price: 59.99, comparePrice: 79.99, costPrice: 22, images: JSON.stringify(['/products/board-game.png']), categoryId: booksMedia.id, stock: 25, sku: 'CLB-BG-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ games: '3-in-1', material: 'Solid Wood', players: '2-6', age: '8+' }), rating: 4.5, reviewCount: 45, soldCount: 234 },
      { name: 'Bestselling Fiction Novel', slug: 'bestselling-fiction-novel', shortDesc: 'The gripping tale of self-discovery', price: 18.99, comparePrice: 24.99, costPrice: 6, images: JSON.stringify(['/products/novel.png']), categoryId: booksMedia.id, stock: 70, sku: 'BSF-FN-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ format: 'Paperback', pages: '352', genre: 'Literary Fiction', isbn: '978-0-987654-32-1' }), rating: 4.4, reviewCount: 134, soldCount: 890 },
      { name: 'Vinyl Record - Jazz Classics', slug: 'vinyl-record-jazz-classics', shortDesc: 'Remastered 180g vinyl', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/headphones.png']), categoryId: booksMedia.id, stock: 20, sku: 'VNR-JC-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ format: 'LP Vinyl', weight: '180g', tracks: '12', remastered: true }), rating: 4.8, reviewCount: 34, soldCount: 156 },
      { name: 'Cookbook: Modern Kitchen', slug: 'cookbook-modern-kitchen', shortDesc: '100 contemporary recipes', price: 32.99, comparePrice: 42.99, costPrice: 10, images: JSON.stringify(['/products/dutch-oven.png']), categoryId: booksMedia.id, stock: 35, sku: 'CBK-MK-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ format: 'Hardcover', pages: '320', recipes: '100', photography: 'Full color' }), rating: 4.6, reviewCount: 56, soldCount: 345 },

      // --- JEWELRY (6) ---
      { name: 'Gold Diamond Ring', slug: 'gold-diamond-ring', shortDesc: '18K gold with 0.75ct diamond', price: 899.99, comparePrice: 1099.99, costPrice: 380, images: JSON.stringify(['/products/gold-ring.png']), categoryId: jewelry.id, stock: 8, sku: 'GLD-DR-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ metal: '18K Yellow Gold', carat: '0.75ct', clarity: 'VS1', setting: 'Solitaire' }), rating: 4.9, reviewCount: 23, soldCount: 67 },
      { name: 'Pearl Necklace', slug: 'pearl-necklace', shortDesc: 'Freshwater pearls, sterling silver clasp', price: 199.99, comparePrice: 259.99, costPrice: 75, images: JSON.stringify(['/products/pearl-necklace.png']), categoryId: jewelry.id, stock: 12, sku: 'PRL-NK-002', isFeatured: true, isNew: false, attributes: JSON.stringify({ type: 'Freshwater Pearl', length: '18"', clasp: 'Sterling Silver', grade: 'AA+' }), rating: 4.7, reviewCount: 34, soldCount: 123 },
      { name: 'Gold Chain Necklace', slug: 'gold-chain-necklace', shortDesc: '14K solid gold, Cuban link', price: 549.99, comparePrice: 699.99, costPrice: 230, images: JSON.stringify(['/products/gold-necklace.png']), categoryId: jewelry.id, stock: 10, sku: 'GLD-CN-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ metal: '14K Solid Gold', style: 'Cuban Link', length: '20"', width: '5mm' }), rating: 4.8, reviewCount: 28, soldCount: 89 },
      { name: 'Rose Gold Bangle Set', slug: 'rose-gold-bangle-set', shortDesc: 'Set of 3 minimalist bangles', price: 179.99, comparePrice: 229.99, costPrice: 65, images: JSON.stringify(['/products/charm-bracelet.png']), categoryId: jewelry.id, stock: 18, sku: 'RGD-BB-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ metal: '14K Rose Gold', pieces: '3', diameter: '2.5"', finish: 'Polished' }), rating: 4.6, reviewCount: 22, soldCount: 78 },
      { name: 'Sapphire Stud Earrings', slug: 'sapphire-stud-earrings', shortDesc: 'Lab-grown sapphires, 14K gold', price: 299.99, comparePrice: 379.99, costPrice: 120, images: JSON.stringify(['/products/diamond-earrings.png']), categoryId: jewelry.id, stock: 15, sku: 'SPH-SE-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ gemstone: 'Lab Sapphire', metal: '14K White Gold', carat: '1.2ct total', setting: '4-Prong' }), rating: 4.7, reviewCount: 19, soldCount: 56 },
      { name: 'Vintage Brooch Pin', slug: 'vintage-brooch-pin', shortDesc: 'Crystal-encrusted floral design', price: 89.99, comparePrice: 119.99, costPrice: 30, images: JSON.stringify(['/products/pearl-necklace.png']), categoryId: jewelry.id, stock: 20, sku: 'VNT-BP-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Gold-plated Brass', crystals: 'Czech', design: 'Floral', size: '4cm' }), rating: 4.5, reviewCount: 16, soldCount: 45 },

      // --- KITCHEN & DINING (6) ---
      { name: 'Ceramic Knife Set', slug: 'ceramic-knife-set', shortDesc: '6-piece zirconia ceramic blades', price: 89.99, comparePrice: 119.99, costPrice: 32, images: JSON.stringify(['/products/ceramic-knives.png']), categoryId: kitchen.id, stock: 25, sku: 'CRM-KS-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '6', blade: 'Zirconia Ceramic', handle: 'Ergonomic ABS', includes: 'Block + 5 knives' }), rating: 4.7, reviewCount: 56, soldCount: 345 },
      { name: 'Premium Dutch Oven', slug: 'premium-dutch-oven', shortDesc: 'Enameled cast iron, 6-quart', price: 129.99, comparePrice: 169.99, costPrice: 50, images: JSON.stringify(['/products/dutch-oven.png']), categoryId: kitchen.id, stock: 18, sku: 'PRM-DO-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Enameled Cast Iron', capacity: '6 Quart', oven_safe: '500°F', color: 'Matte Black' }), rating: 4.8, reviewCount: 78, soldCount: 567 },
      { name: 'Cast Iron Skillet', slug: 'cast-iron-skillet', shortDesc: 'Pre-seasoned, 12-inch', price: 49.99, comparePrice: 64.99, costPrice: 18, images: JSON.stringify(['/products/skillet.png']), categoryId: kitchen.id, stock: 30, sku: 'CIS-12-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Cast Iron', size: '12"', pre_seasoned: true, oven_safe: '500°F' }), rating: 4.6, reviewCount: 89, soldCount: 678 },
      { name: 'Chef\'s Knife Pro', slug: 'chefs-knife-pro', shortDesc: '8-inch Japanese steel blade', price: 119.99, comparePrice: 149.99, costPrice: 45, images: JSON.stringify(['/products/knife-set.png']), categoryId: kitchen.id, stock: 22, sku: 'CHF-KP-004', isFeatured: true, isNew: false, attributes: JSON.stringify({ blade: 'VG-10 Japanese Steel', length: '8"', handle: 'Pakkawood', hrc: '61' }), rating: 4.9, reviewCount: 45, soldCount: 234 },
      { name: 'Electric Kettle - Gooseneck', slug: 'electric-kettle-gooseneck', shortDesc: 'Precision pour, variable temp', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/steel-bottle.png']), categoryId: kitchen.id, stock: 28, sku: 'ELK-GN-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ capacity: '1L', temp_range: '140-212°F', material: 'Stainless Steel', wattage: '1200W' }), rating: 4.7, reviewCount: 34, soldCount: 178 },
      { name: 'Bamboo Cutting Board Set', slug: 'bamboo-cutting-board-set', shortDesc: 'Set of 3, juice grooves', price: 39.99, comparePrice: 54.99, costPrice: 12, images: JSON.stringify(['/products/desk-organizer.png']), categoryId: kitchen.id, stock: 35, sku: 'BMB-CB-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '3 (S/M/L)', material: 'Organic Bamboo', features: 'Juice grooves + Handles', care: 'Hand wash' }), rating: 4.5, reviewCount: 56, soldCount: 345 },

      // --- AUTOMOTIVE (6) ---
      { name: 'Magnetic Car Phone Mount', slug: 'magnetic-car-phone-mount', shortDesc: 'Strong neodymium magnets, 360° rotation', price: 29.99, comparePrice: 39.99, costPrice: 8, images: JSON.stringify(['/products/car-mount.png']), categoryId: automotive.id, stock: 50, sku: 'MAG-CM-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ mount_type: 'Dashboard/Vent', magnet: 'Neodymium N52', rotation: '360°', compatible: 'All phones' }), rating: 4.6, reviewCount: 89, soldCount: 567 },
      { name: 'Leather Car Steering Cover', slug: 'leather-car-steering-cover', shortDesc: 'Premium genuine leather, anti-slip', price: 44.99, comparePrice: 59.99, costPrice: 15, images: JSON.stringify(['/products/dog-collar.png']), categoryId: automotive.id, stock: 30, sku: 'LTH-SC-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Genuine Leather', size: '14.5-15"', inner: 'Anti-slip rubber', colors: 'Black/Brown' }), rating: 4.5, reviewCount: 45, soldCount: 234 },
      { name: 'Car Jump Starter Kit', slug: 'car-jump-starter-kit', shortDesc: '2000A peak, built-in LED light', price: 89.99, comparePrice: 119.99, costPrice: 35, images: JSON.stringify(['/products/charging-station.png']), categoryId: automotive.id, stock: 20, sku: 'CAR-JS-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ peak_current: '2000A', battery: '20000mAh', led: 'SOS/Strobe', ports: 'USB-C + USB-A' }), rating: 4.7, reviewCount: 34, soldCount: 178 },
      { name: 'Car Vacuum Cleaner', slug: 'car-vacuum-cleaner', shortDesc: 'Cordless, powerful suction', price: 59.99, comparePrice: 79.99, costPrice: 20, images: JSON.stringify(['/products/dash-cam.png']), categoryId: automotive.id, stock: 25, sku: 'CAR-VC-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ power: '120W', suction: '8000Pa', battery: '4000mAh', attachments: '3 nozzles' }), rating: 4.4, reviewCount: 56, soldCount: 345 },
      { name: 'Tire Inflator Portable', slug: 'tire-inflator-portable', shortDesc: 'Digital preset, auto shutoff', price: 69.99, comparePrice: 89.99, costPrice: 25, images: JSON.stringify(['/products/bluetooth-speaker.png']), categoryId: automotive.id, stock: 22, sku: 'TRI-PI-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ max_psi: '150 PSI', power: '12V DC', display: 'Digital LED', auto_shutoff: true }), rating: 4.5, reviewCount: 38, soldCount: 189 },
      { name: 'Dashboard Camera 1080p', slug: 'dashboard-camera-1080p', shortDesc: 'Compact, wide-angle, night vision', price: 49.99, comparePrice: 69.99, costPrice: 18, images: JSON.stringify(['/products/dash-cam.png']), categoryId: automotive.id, stock: 35, sku: 'DBC-1080-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ resolution: '1080p', angle: '170°', night_vision: true, screen: '2.4"' }), rating: 4.3, reviewCount: 42, soldCount: 234 },

      // --- GARDEN & OUTDOOR (6) ---
      { name: 'Professional Pruning Tools', slug: 'professional-pruning-tools', shortDesc: '3-piece garden tool set', price: 59.99, comparePrice: 79.99, costPrice: 20, images: JSON.stringify(['/products/pruning-tools.png']), categoryId: garden.id, stock: 25, sku: 'PRO-PT-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '3 (Bypass/Loppers/Saw)', material: 'SK5 Steel', handles: 'Aluminum', warranty: '2 years' }), rating: 4.7, reviewCount: 45, soldCount: 234 },
      { name: 'Smart Garden Kit', slug: 'smart-garden-kit', shortDesc: 'Indoor herb garden with LED grow light', price: 99.99, comparePrice: 129.99, costPrice: 38, images: JSON.stringify(['/products/monstera.png']), categoryId: garden.id, stock: 18, sku: 'SMR-GK-002', isFeatured: true, isNew: false, attributes: JSON.stringify({ pods: '6', light: 'LED Full Spectrum', timer: 'Auto 16hr on/8hr off', includes: 'Starter pod kit' }), rating: 4.8, reviewCount: 34, soldCount: 178 },
      { name: 'Garden Tool Set', slug: 'garden-tool-set', shortDesc: '9-piece stainless steel with bag', price: 44.99, comparePrice: 59.99, costPrice: 15, images: JSON.stringify(['/products/garden-tools.png']), categoryId: garden.id, stock: 30, sku: 'GRD-TS-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '9', material: 'Stainless Steel', bag: 'Canvas Tote', rust_resistant: true }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Outdoor Solar Lights Set', slug: 'outdoor-solar-lights-set', shortDesc: '8-pack pathway lights, auto on/off', price: 39.99, comparePrice: 54.99, costPrice: 12, images: JSON.stringify(['/products/led-bulbs.png']), categoryId: garden.id, stock: 35, sku: 'OTD-SL-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ pieces: '8', power: 'Solar', brightness: '15 lumens', waterproof: 'IP65' }), rating: 4.4, reviewCount: 45, soldCount: 267 },
      { name: 'Raised Garden Bed Kit', slug: 'raised-garden-bed-kit', shortDesc: 'Cedar wood, 4x4ft, easy assembly', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/plant-pot.png']), categoryId: garden.id, stock: 15, sku: 'RGB-44-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Cedar Wood', size: '4x4ft', height: '11"', assembly: 'No tools' }), rating: 4.6, reviewCount: 23, soldCount: 123 },
      { name: 'Plant Grow Lights', slug: 'plant-grow-lights', shortDesc: 'Full spectrum, clip-on, dimmable', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/brass-lamp.png']), categoryId: garden.id, stock: 28, sku: 'PGL-FS-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ spectrum: 'Full', power: '15W', timer: 'Auto on/off', clip: 'Strong clamp' }), rating: 4.5, reviewCount: 34, soldCount: 189 },

      // --- PET SUPPLIES (6) ---
      { name: 'Premium Dog Treats', slug: 'premium-dog-treats', shortDesc: 'Organic, grain-free, 3-flavor pack', price: 24.99, comparePrice: 32.99, costPrice: 8, images: JSON.stringify(['/products/dog-treats.png']), categoryId: petSupplies.id, stock: 45, sku: 'PRM-DT-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ flavors: 'Chicken/Beef/Salmon', organic: true, grain_free: true, weight: '300g' }), rating: 4.7, reviewCount: 67, soldCount: 456 },
      { name: 'Adjustable Dog Collar', slug: 'adjustable-dog-collar', shortDesc: 'Premium nylon, padded, reflective', price: 19.99, comparePrice: 27.99, costPrice: 6, images: JSON.stringify(['/products/dog-collar.png']), categoryId: petSupplies.id, stock: 40, sku: 'ADJ-DC-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Nylon + Padding', sizes: 'S/M/L/XL', reflective: true, buckle: 'Metal' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Cat Tree Tower', slug: 'cat-tree-tower', shortDesc: '5-level with scratching posts', price: 129.99, comparePrice: 169.99, costPrice: 48, images: JSON.stringify(['/products/cat-tower.png']), categoryId: petSupplies.id, stock: 12, sku: 'CTT-5L-003', isFeatured: true, isNew: false, attributes: JSON.stringify({ levels: '5', height: '72"', material: 'Sisal + Plush', weight_capacity: '40lbs' }), rating: 4.6, reviewCount: 34, soldCount: 178 },
      { name: 'Luxury Cat Tree', slug: 'luxury-cat-tree', shortDesc: 'Modern design with hideaway condo', price: 159.99, comparePrice: 199.99, costPrice: 60, images: JSON.stringify(['/products/cat-tree.png']), categoryId: petSupplies.id, stock: 10, sku: 'LUX-CT-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ levels: '4', features: 'Condo + Hammock + Scratching', material: 'Faux Fur + Sisal', color: 'Gray' }), rating: 4.7, reviewCount: 23, soldCount: 89 },
      { name: 'Pet Grooming Kit', slug: 'pet-grooming-kit', shortDesc: 'Professional 8-piece grooming set', price: 34.99, comparePrice: 49.99, costPrice: 12, images: JSON.stringify(['/products/dog-collar.png']), categoryId: petSupplies.id, stock: 28, sku: 'PET-GK-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '8', includes: 'Clippers/Scissors/Brush/Comb/Nail Trimmer', suitable: 'Dogs & Cats', case: 'Storage bag' }), rating: 4.4, reviewCount: 45, soldCount: 267 },
      { name: 'Orthopedic Dog Bed', slug: 'orthopedic-dog-bed', shortDesc: 'Memory foam, waterproof liner', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/blanket.png']), categoryId: petSupplies.id, stock: 18, sku: 'ODO-DB-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Memory Foam', cover: 'Machine washable', waterproof: true, sizes: 'M/L/XL' }), rating: 4.8, reviewCount: 34, soldCount: 178 },

      // --- OFFICE & STATIONERY (6) ---
      { name: 'Leather Desk Pad', slug: 'leather-desk-pad', shortDesc: 'Full-grain leather, large format', price: 69.99, comparePrice: 89.99, costPrice: 24, images: JSON.stringify(['/products/desk-pad.png']), categoryId: office.id, stock: 25, sku: 'LTH-DP-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ material: 'Full-grain Leather', size: '35"x17"', color: 'Dark Brown', anti_slip: 'Felt base' }), rating: 4.7, reviewCount: 45, soldCount: 234 },
      { name: 'Bamboo Desk Organizer', slug: 'bamboo-desk-organizer', shortDesc: 'Multi-compartment, phone stand', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/desk-organizer.png']), categoryId: office.id, stock: 30, sku: 'BMB-DO-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Bamboo', compartments: '6', phone_stand: true, drawer: '1' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Ergonomic Standing Desk', slug: 'ergonomic-standing-desk', shortDesc: 'Electric height-adjustable, 60"', price: 499.99, comparePrice: 649.99, costPrice: 220, images: JSON.stringify(['/products/standing-desk.png']), categoryId: office.id, stock: 8, sku: 'ERG-SD-003', isFeatured: true, isNew: false, attributes: JSON.stringify({ size: '60"x30"', height_range: '28"-48"', motor: 'Dual', weight_capacity: '300lbs' }), rating: 4.8, reviewCount: 34, soldCount: 89 },
      { name: 'Premium Pen Set', slug: 'premium-pen-set', shortDesc: '3 pens with gift box', price: 49.99, comparePrice: 64.99, costPrice: 16, images: JSON.stringify(['/products/journal.png']), categoryId: office.id, stock: 22, sku: 'PRM-PS-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ pens: '3 (Ballpoint/Rollerball/Fountain)', material: 'Brass + Chrome', refillable: true, gift_box: true }), rating: 4.6, reviewCount: 34, soldCount: 178 },
      { name: 'Monitor Stand Riser', slug: 'monitor-stand-riser', shortDesc: 'Bamboo, adjustable, with storage', price: 44.99, comparePrice: 59.99, costPrice: 15, images: JSON.stringify(['/products/bamboo-cutting-board-set.png']), categoryId: office.id, stock: 20, sku: 'MNS-MR-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Bamboo', width: '23.5"', height: '3.5"/5.5"', storage: 'Drawer + shelf', weight_capacity: '80lbs' }), rating: 4.4, reviewCount: 28, soldCount: 156 },
      { name: 'Wireless Charging Mouse Pad', slug: 'wireless-charging-mouse-pad', shortDesc: 'Large pad with built-in Qi charger', price: 39.99, comparePrice: 54.99, costPrice: 14, images: JSON.stringify(['/products/desk-pad.png']), categoryId: office.id, stock: 25, sku: 'WCM-MP-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ size: '31"x13"', charging: 'Qi 10W', material: 'PU Leather + Microfiber', led: 'Indicator light' }), rating: 4.5, reviewCount: 38, soldCount: 234 },

      // --- HEALTH & WELLNESS (6) ---
      { name: 'Digital Thermometer Pro', slug: 'digital-thermometer-pro', shortDesc: 'Instant reading, no-touch infrared', price: 39.99, comparePrice: 54.99, costPrice: 12, images: JSON.stringify(['/products/thermometer.png']), categoryId: health.id, stock: 35, sku: 'DGT-TP-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ type: 'Infrared No-Touch', reading_time: '1 second', memory: '32 readings', display: 'Backlit LCD' }), rating: 4.6, reviewCount: 67, soldCount: 456 },
      { name: 'Aromatherapy Diffuser', slug: 'aromatherapy-diffuser', shortDesc: 'Ultrasonic, 500ml, ambient lighting', price: 49.99, comparePrice: 64.99, costPrice: 16, images: JSON.stringify(['/products/essential-oils.png']), categoryId: health.id, stock: 30, sku: 'ARO-DF-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ capacity: '500ml', runtime: '10 hours', mist: 'Ultrasonic cool', light: '7-color LED' }), rating: 4.7, reviewCount: 89, soldCount: 567 },
      { name: 'Neck & Shoulder Massager', slug: 'neck-shoulder-massager', shortDesc: 'Shiatsu, heat, portable', price: 79.99, comparePrice: 99.99, costPrice: 28, images: JSON.stringify(['/products/thermometer.png']), categoryId: health.id, stock: 22, sku: 'NSM-SH-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ type: 'Shiatsu', heat: 'Infrared', nodes: '8 deep-kneading', power: 'Rechargeable' }), rating: 4.5, reviewCount: 56, soldCount: 345 },
      { name: 'Smart Body Scale', slug: 'smart-body-scale', shortDesc: '13 body metrics, Bluetooth app', price: 49.99, comparePrice: 69.99, costPrice: 18, images: JSON.stringify(['/products/phone-mount.png']), categoryId: health.id, stock: 28, sku: 'SBS-BT-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ metrics: '13', connectivity: 'Bluetooth', users: '8', platform: 'iOS/Android' }), rating: 4.6, reviewCount: 45, soldCount: 267 },
      { name: 'Acupressure Mat & Pillow', slug: 'acupressure-mat-pillow', shortDesc: 'Relieve stress, improve sleep', price: 34.99, comparePrice: 49.99, costPrice: 10, images: JSON.stringify(['/products/yoga-mat.png']), categoryId: health.id, stock: 32, sku: 'ACU-MP-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Cotton + Foam', points: '7,742 acupressure', includes: 'Mat + Pillow', cover: 'Removable washable' }), rating: 4.4, reviewCount: 38, soldCount: 234 },
      { name: 'Sleep Mask Premium', slug: 'sleep-mask-premium', shortDesc: '3D contour, 100% blackout', price: 19.99, comparePrice: 29.99, costPrice: 6, images: JSON.stringify(['/products/essential-oils.png']), categoryId: health.id, stock: 50, sku: 'SLM-PM-006', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Silk + Memory Foam', blackout: '100%', strap: 'Adjustable', breathable: true }), rating: 4.5, reviewCount: 78, soldCount: 567 },

      // --- BABY & KIDS (6) ---
      { name: 'Organic Baby Care Set', slug: 'organic-baby-care-set', shortDesc: 'Lotion, shampoo, wash, 3-piece', price: 39.99, comparePrice: 54.99, costPrice: 14, images: JSON.stringify(['/products/baby-care.png']), categoryId: baby.id, stock: 30, sku: 'ORG-BC-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '3', organic: true, fragrance_free: true, size: '250ml each' }), rating: 4.7, reviewCount: 56, soldCount: 345 },
      { name: 'Premium Stroller', slug: 'premium-stroller', shortDesc: 'Lightweight, one-hand fold, all-terrain', price: 449.99, comparePrice: 549.99, costPrice: 190, images: JSON.stringify(['/products/stroller.png']), categoryId: baby.id, stock: 8, sku: 'PRM-ST-002', isFeatured: true, isNew: false, attributes: JSON.stringify({ weight: '18lbs', fold: 'One-hand', wheels: 'All-terrain rubber', age: '0-4 years' }), rating: 4.8, reviewCount: 23, soldCount: 78 },
      { name: 'Cotton Baby Onesie Set', slug: 'cotton-baby-onesie-set', shortDesc: '5-pack organic cotton, pastel', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/baby-onesie.png']), categoryId: baby.id, stock: 35, sku: 'CTN-BO-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '5', material: '100% Organic Cotton', sizes: '0-3/3-6/6-12 months', colors: 'Pastel set' }), rating: 4.6, reviewCount: 67, soldCount: 456 },
      { name: 'Plush Teddy Bear', slug: 'plush-teddy-bear', shortDesc: 'Ultra-soft, hypoallergenic, 16"', price: 29.99, comparePrice: 39.99, costPrice: 10, images: JSON.stringify(['/products/teddy-bear.png']), categoryId: baby.id, stock: 25, sku: 'PLS-TB-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ size: '16"', material: 'Plush + PP Cotton', hypoallergenic: true, washing: 'Machine washable' }), rating: 4.8, reviewCount: 45, soldCount: 267 },
      { name: 'Baby Monitor WiFi', slug: 'baby-monitor-wifi', shortDesc: '1080p, night vision, two-way audio', price: 149.99, comparePrice: 189.99, costPrice: 55, images: JSON.stringify(['/products/dash-cam.png']), categoryId: baby.id, stock: 15, sku: 'BAM-WF-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ resolution: '1080p', night_vision: 'IR', audio: 'Two-way', app: 'iOS/Android' }), rating: 4.5, reviewCount: 34, soldCount: 178 },
      { name: 'Wooden Baby Rattle Set', slug: 'wooden-baby-rattle-set', shortDesc: '3 organic wood rattles', price: 19.99, comparePrice: 27.99, costPrice: 6, images: JSON.stringify(['/products/building-blocks.png']), categoryId: baby.id, stock: 28, sku: 'WBR-RS-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '3', material: 'Beech Wood', finish: 'Food-grade oil', age: '3+ months' }), rating: 4.4, reviewCount: 34, soldCount: 189 },

      // --- TOYS & GAMES (6) ---
      { name: 'Magnetic Building Blocks', slug: 'magnetic-building-blocks', shortDesc: '100-piece STEM learning set', price: 54.99, comparePrice: 69.99, costPrice: 18, images: JSON.stringify(['/products/building-blocks.png']), categoryId: toys.id, stock: 22, sku: 'MGB-100-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '100', material: 'ABS Plastic + Magnetic', age: '3+', features: 'STEM learning' }), rating: 4.7, reviewCount: 56, soldCount: 345 },
      { name: 'Wooden Puzzle Toy Set', slug: 'wooden-puzzle-toy-set', shortDesc: '4-pack educational puzzles', price: 29.99, comparePrice: 39.99, costPrice: 10, images: JSON.stringify(['/products/puzzle-toy.png']), categoryId: toys.id, stock: 30, sku: 'WPT-4P-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ puzzles: '4', material: 'Wood', pieces: '12-24 per puzzle', age: '2-5 years' }), rating: 4.5, reviewCount: 45, soldCount: 267 },
      { name: 'RC Racing Car Pro', slug: 'rc-racing-car-pro', shortDesc: '1:16 scale, 2.4GHz, 30mph', price: 89.99, comparePrice: 119.99, costPrice: 35, images: JSON.stringify(['/products/gaming-mouse.png']), categoryId: toys.id, stock: 18, sku: 'RCC-PR-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ scale: '1:16', speed: '30mph', remote: '2.4GHz', battery: '30 min run time' }), rating: 4.6, reviewCount: 34, soldCount: 178 },
      { name: 'Strategy Board Game', slug: 'strategy-board-game', shortDesc: 'Award-winning, 2-5 players', price: 44.99, comparePrice: 54.99, costPrice: 16, images: JSON.stringify(['/products/board-game.png']), categoryId: toys.id, stock: 25, sku: 'SBG-AW-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ players: '2-5', age: '10+', play_time: '60-120 min', award: 'Game of the Year' }), rating: 4.8, reviewCount: 78, soldCount: 567 },
      { name: 'Art Supply Kit for Kids', slug: 'art-supply-kit-kids', shortDesc: '150-piece creative set', price: 39.99, comparePrice: 54.99, costPrice: 14, images: JSON.stringify(['/products/puzzle-toy.png']), categoryId: toys.id, stock: 28, sku: 'ASK-150-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '150', includes: 'Crayons/Markers/Paint/Brushes/Paper', age: '4+', case: 'Portable case' }), rating: 4.5, reviewCount: 45, soldCount: 345 },
      { name: 'Drone with Camera', slug: 'drone-with-camera', shortDesc: '4K camera, GPS, foldable', price: 199.99, comparePrice: 259.99, costPrice: 80, images: JSON.stringify(['/products/dash-cam.png']), categoryId: toys.id, stock: 12, sku: 'DRN-4K-006', isFeatured: true, isNew: true, attributes: JSON.stringify({ camera: '4K', gps: true, flight_time: '30 min', range: '500m' }), rating: 4.6, reviewCount: 23, soldCount: 89 },

      // --- TRAVEL & LUGGAGE (6) ---
      { name: 'Premium Carry-On Suitcase', slug: 'premium-carry-on-suitcase', shortDesc: 'Hard shell, TSA lock, spinner wheels', price: 229.99, comparePrice: 299.99, costPrice: 90, images: JSON.stringify(['/products/suitcase.png']), categoryId: travel.id, stock: 15, sku: 'PRM-CS-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ size: '22x14x9"', material: 'Polycarbonate', wheels: '4 Spinner', lock: 'TSA-approved' }), rating: 4.8, reviewCount: 45, soldCount: 234 },
      { name: 'Travel Neck Pillow', slug: 'travel-neck-pillow', shortDesc: 'Memory foam, washable cover', price: 29.99, comparePrice: 39.99, costPrice: 10, images: JSON.stringify(['/products/blanket.png']), categoryId: travel.id, stock: 40, sku: 'TRV-NP-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ material: 'Memory Foam', cover: 'Machine washable', portability: 'Snap loop', support: '360° chin' }), rating: 4.5, reviewCount: 78, soldCount: 567 },
      { name: 'Packing Cubes Set', slug: 'packing-cubes-set', shortDesc: '6-piece, compression, waterproof', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/messenger-bag.png']), categoryId: travel.id, stock: 35, sku: 'PKC-6P-003', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '6', material: 'Nylon', compression: true, waterproof: true }), rating: 4.6, reviewCount: 89, soldCount: 678 },
      { name: 'Travel Toiletry Bag', slug: 'travel-toiletry-bag', shortDesc: 'Hanging, waterproof, large capacity', price: 24.99, comparePrice: 34.99, costPrice: 8, images: JSON.stringify(['/products/leather-bag.png']), categoryId: travel.id, stock: 38, sku: 'TRV-TB-004', isFeatured: false, isNew: true, attributes: JSON.stringify({ material: 'Waterproof Nylon', hanging: 'Hook included', pockets: '4 zippered', size: '10x7x4"' }), rating: 4.4, reviewCount: 56, soldCount: 345 },
      { name: 'Luggage Tag Set', slug: 'luggage-tag-set', shortDesc: '4-pack leather, GPS slot', price: 19.99, comparePrice: 27.99, costPrice: 6, images: JSON.stringify(['/products/wallet.png']), categoryId: travel.id, stock: 45, sku: 'LUG-TS-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ pieces: '4', material: 'PU Leather', gps_slot: true, info_card: 'Included' }), rating: 4.3, reviewCount: 34, soldCount: 234 },
      { name: 'Travel Adapter Universal', slug: 'travel-adapter-universal', shortDesc: '200+ countries, 4 USB ports', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/charging-station.png']), categoryId: travel.id, stock: 30, sku: 'TRA-UA-006', isFeatured: false, isNew: false, attributes: JSON.stringify({ countries: '200+', usb_ports: '4 (65W total)', safety: 'Fuse protection', plug_types: 'US/EU/UK/AU' }), rating: 4.6, reviewCount: 67, soldCount: 456 },

      // --- HOME IMPROVEMENT (5) ---
      { name: 'Smart LED Bulb Kit', slug: 'smart-led-bulb-kit', shortDesc: '4-pack, dimmable, voice control', price: 39.99, comparePrice: 54.99, costPrice: 14, images: JSON.stringify(['/products/led-bulbs.png']), categoryId: homeImprove.id, stock: 30, sku: 'SML-BK-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ pieces: '4', wattage: '9W (60W equiv)', colors: '16 million', compatible: 'Alexa/Google/HomeKit' }), rating: 4.7, reviewCount: 78, soldCount: 567 },
      { name: 'Smart Plug Mini', slug: 'smart-plug-mini', shortDesc: 'WiFi, voice control, energy monitor', price: 14.99, comparePrice: 19.99, costPrice: 5, images: JSON.stringify(['/products/phone-mount.png']), categoryId: homeImprove.id, stock: 50, sku: 'SPL-MN-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ connectivity: 'WiFi', max_load: '15A/1800W', voice: 'Alexa/Google', scheduling: true }), rating: 4.5, reviewCount: 89, soldCount: 678 },
      { name: 'LED Strip Lights', slug: 'led-strip-lights', shortDesc: '32.8ft, RGB, music sync', price: 24.99, comparePrice: 34.99, costPrice: 8, images: JSON.stringify(['/products/led-bulbs.png']), categoryId: homeImprove.id, stock: 40, sku: 'LDS-32-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ length: '32.8ft', color: 'RGB', sync: 'Music reactive', control: 'App + Remote' }), rating: 4.4, reviewCount: 56, soldCount: 345 },
      { name: 'Motion Sensor Light', slug: 'motion-sensor-light', shortDesc: 'Rechargeable, 3 modes, magnetic', price: 19.99, comparePrice: 27.99, costPrice: 6, images: JSON.stringify(['/products/brass-lamp.png']), categoryId: homeImprove.id, stock: 35, sku: 'MSL-RC-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ power: 'Rechargeable', modes: '3 (On/Off/Auto)', sensor: 'PIR 120°', mount: 'Magnetic' }), rating: 4.3, reviewCount: 45, soldCount: 267 },
      { name: 'Fire Extinguisher Home', slug: 'fire-extinguisher-home', shortDesc: 'Compact, 2.5lb, ABC rated', price: 34.99, comparePrice: 44.99, costPrice: 12, images: JSON.stringify(['/products/steel-bottle.png']), categoryId: homeImprove.id, stock: 20, sku: 'FEH-25-005', isFeatured: false, isNew: false, attributes: JSON.stringify({ type: 'ABC Dry Chemical', weight: '2.5lb', rating: '1A:10B:C', ul: 'UL Listed' }), rating: 4.6, reviewCount: 23, soldCount: 123 },

      // --- MUSIC & AUDIO (6) ---
      { name: 'Premium Bluetooth Speaker', slug: 'premium-bluetooth-speaker', shortDesc: '360° sound, 24hr battery, waterproof', price: 149.99, comparePrice: 189.99, costPrice: 55, images: JSON.stringify(['/products/bluetooth-speaker.png']), categoryId: music.id, stock: 20, sku: 'PBT-SP-001', isFeatured: true, isNew: true, attributes: JSON.stringify({ power: '30W', battery: '24 hours', waterproof: 'IPX7', weight: '780g' }), rating: 4.8, reviewCount: 56, soldCount: 345 },
      { name: 'Studio Monitor Headphones', slug: 'studio-monitor-headphones', shortDesc: 'Professional, open-back, flat response', price: 199.99, comparePrice: 249.99, costPrice: 80, images: JSON.stringify(['/products/headphones.png']), categoryId: music.id, stock: 15, sku: 'SMH-PR-002', isFeatured: false, isNew: false, attributes: JSON.stringify({ type: 'Open-back', driver: '50mm', impedance: '250 Ohm', cable: 'Detachable 3m' }), rating: 4.7, reviewCount: 34, soldCount: 178 },
      { name: 'USB Condenser Microphone', slug: 'usb-condenser-microphone', shortDesc: 'Plug-and-play, studio quality', price: 119.99, comparePrice: 149.99, costPrice: 42, images: JSON.stringify(['/products/bt-speaker.png']), categoryId: music.id, stock: 18, sku: 'UCM-SQ-003', isFeatured: false, isNew: true, attributes: JSON.stringify({ type: 'Condenser', connection: 'USB-C', sample_rate: '96kHz/24bit', includes: 'Boom arm + pop filter' }), rating: 4.6, reviewCount: 23, soldCount: 134 },
      { name: 'Guitar Tuner Clip-On', slug: 'guitar-tuner-clip-on', shortDesc: 'Fast, accurate, color display', price: 14.99, comparePrice: 19.99, costPrice: 4, images: JSON.stringify(['/products/phone-mount.png']), categoryId: music.id, stock: 45, sku: 'GTC-CO-004', isFeatured: false, isNew: false, attributes: JSON.stringify({ type: 'Chromatic Clip-on', accuracy: '±1 cent', display: 'Color LCD', battery: 'CR2032' }), rating: 4.5, reviewCount: 45, soldCount: 345 },
      { name: 'Electronic Drum Pad', slug: 'electronic-drum-pad', shortDesc: '8-pad, built-in sounds, MIDI', price: 149.99, comparePrice: 189.99, costPrice: 55, images: JSON.stringify(['/products/keyboard.png']), categoryId: music.id, stock: 12, sku: 'EDP-8P-005', isFeatured: false, isNew: true, attributes: JSON.stringify({ pads: '8 velocity-sensitive', sounds: '100+', midi: 'USB MIDI', power: 'USB/AA' }), rating: 4.4, reviewCount: 18, soldCount: 89 },
      { name: 'Vinyl Record Player', slug: 'vinyl-record-player', shortDesc: 'Belt-drive, built-in preamp, Bluetooth', price: 179.99, comparePrice: 229.99, costPrice: 70, images: JSON.stringify(['/products/novel.png']), categoryId: music.id, stock: 10, sku: 'VRP-BD-006', isFeatured: true, isNew: false, attributes: JSON.stringify({ drive: 'Belt', speed: '33/45/78 RPM', preamp: 'Built-in phono', bluetooth: 'BT 5.0 output' }), rating: 4.7, reviewCount: 28, soldCount: 123 },
    ];

    for (const p of products) {
      await db.product.create({ data: p });
    }

    // ==================== REVIEWS (130) ====================
    const reviewData = [
      { name: 'Sarah M.', rating: 5, text: 'Absolutely love this! Quality exceeded my expectations.' },
      { name: 'James K.', rating: 5, text: 'Best purchase I\'ve made this year. Highly recommend!' },
      { name: 'Emily R.', rating: 4, text: 'Great product, fast shipping. Very satisfied.' },
      { name: 'Michael T.', rating: 5, text: 'Premium quality at a fair price. Will buy again.' },
      { name: 'Jessica L.', rating: 4, text: 'Beautiful design and solid build. Exactly what I wanted.' },
      { name: 'David W.', rating: 5, text: 'This is exactly what I was looking for. Perfect!' },
      { name: 'Amanda H.', rating: 5, text: 'Exceeded all expectations. The quality is outstanding.' },
      { name: 'Robert P.', rating: 4, text: 'Very good value for money. Arrived well-packaged.' },
      { name: 'Lisa C.', rating: 5, text: 'I\'ve been recommending this to everyone. Simply amazing.' },
      { name: 'Thomas B.', rating: 4, text: 'Solid construction, works perfectly. Great buy.' },
      { name: 'Rachel G.', rating: 5, text: 'The craftsmanship is incredible. Worth every penny.' },
      { name: 'Christopher N.', rating: 5, text: 'Couldn\'t be happier with this purchase!' },
      { name: 'Megan S.', rating: 4, text: 'Exactly as described. Shipping was quick too.' },
      { name: 'Andrew D.', rating: 5, text: 'Outstanding quality and attention to detail.' },
      { name: 'Stephanie F.', rating: 5, text: 'This has become my favorite item. Love it!' },
      { name: 'Mark J.', rating: 4, text: 'Good quality, reasonable price. No complaints.' },
      { name: 'Nicole A.', rating: 5, text: 'Beautiful and functional. What more could you ask for?' },
      { name: 'Kevin R.', rating: 5, text: 'Premium feel, premium quality. 10/10 would recommend.' },
      { name: 'Laura E.', rating: 4, text: 'Very happy with my purchase. Great customer service too.' },
      { name: 'Brian M.', rating: 5, text: 'This is a game-changer. Absolutely fantastic.' },
    ];

    const createdProducts = await db.product.findMany({ select: { id: true } });
    const reviewPromises = [];
    for (let i = 0; i < createdProducts.length; i++) {
      const product = createdProducts[i];
      const numReviews = Math.floor(Math.random() * 3) + 1; // 1-3 reviews per product
      for (let j = 0; j < numReviews; j++) {
        const review = reviewData[(i * 3 + j) % reviewData.length];
        reviewPromises.push(
          db.review.create({
            data: {
              productId: product.id,
              userName: review.name,
              rating: review.rating,
              comment: review.text,
              isApproved: true,
            },
          })
        );
      }
    }
    await Promise.all(reviewPromises);

    // ==================== COUPONS ====================
    await db.coupon.createMany({
      data: [
        { code: 'WELCOME10', type: 'percentage', value: 10, minOrder: 0, maxUses: 100, usedCount: 34, isActive: true, expiresAt: new Date('2026-12-31') },
        { code: 'SAVE20', type: 'percentage', value: 20, minOrder: 100, maxUses: 50, usedCount: 12, isActive: true, expiresAt: new Date('2026-06-30') },
        { code: 'FLAT15', type: 'fixed', value: 15, minOrder: 75, maxUses: 200, usedCount: 78, isActive: true, expiresAt: new Date('2026-12-31') },
        { code: 'MEGA25', type: 'percentage', value: 25, minOrder: 150, maxUses: 30, usedCount: 5, isActive: true, expiresAt: new Date('2026-09-30') },
        { code: 'FREESHIP', type: 'fixed', value: 5.99, minOrder: 25, maxUses: 500, usedCount: 156, isActive: true, expiresAt: new Date('2026-12-31') },
      ],
    });

    // ==================== USERS ====================
    await db.user.createMany({
      data: [
        { email: 'admin@shopwithfaisu.com', name: 'Faisu Admin', password: 'admin123', role: 'admin', isActive: true },
        { email: 'customer@example.com', name: 'John Customer', password: 'customer123', role: 'customer', isActive: true },
      ],
    });

    // ==================== SETTINGS ====================
    const settings = [
      { key: 'storeName', value: 'Shop with Faisu!!', group: 'general', label: 'Store Name' },
      { key: 'storeTagline', value: 'Where Style Meets Simplicity', group: 'general', label: 'Store Tagline' },
      { key: 'storeDescription', value: 'Discover curated collections of premium products at Shop with Faisu!!. Clean design, fair prices, exceptional quality.', group: 'general', label: 'Store Description' },
      { key: 'storeLogo', value: '', group: 'general', label: 'Store Logo URL' },
      { key: 'storeFavicon', value: '', group: 'general', label: 'Favicon URL' },
      { key: 'primaryColor', value: '#1a1a1a', group: 'appearance', label: 'Primary Color' },
      { key: 'accentColor', value: '#e8a838', group: 'appearance', label: 'Accent Color' },
      { key: 'currency', value: 'USD', group: 'regional', label: 'Currency' },
      { key: 'currencySymbol', value: '$', group: 'regional', label: 'Currency Symbol' },
      { key: 'freeShippingThreshold', value: '75', group: 'shipping', label: 'Free Shipping Threshold' },
      { key: 'taxRate', value: '0', group: 'regional', label: 'Tax Rate (%)' },
      { key: 'contactEmail', value: 'hello@shopwithfaisu.com', group: 'contact', label: 'Contact Email' },
      { key: 'contactPhone', value: '+1 (555) 123-4567', group: 'contact', label: 'Contact Phone' },
      { key: 'address', value: '123 Faisu Avenue, New York, NY 10001', group: 'contact', label: 'Address' },
      { key: 'socialFacebook', value: 'https://facebook.com/shopwithfaisu', group: 'social', label: 'Facebook URL' },
      { key: 'socialInstagram', value: 'https://instagram.com/shopwithfaisu', group: 'social', label: 'Instagram URL' },
      { key: 'socialTwitter', value: 'https://twitter.com/shopwithfaisu', group: 'social', label: 'Twitter URL' },
      { key: 'socialYoutube', value: 'https://youtube.com/@shopwithfaisu', group: 'social', label: 'YouTube URL' },
      { key: 'heroTitle', value: 'Everything You Need, Beautifully Curated', group: 'homepage', label: 'Hero Title' },
      { key: 'heroSubtitle', value: '20 categories. 126+ products. One destination. Free shipping on orders over $75.', group: 'homepage', label: 'Hero Subtitle' },
      { key: 'heroCta', value: 'Shop Now', group: 'homepage', label: 'Hero CTA Text' },
      { key: 'heroImage', value: '', group: 'homepage', label: 'Hero Image URL' },
      { key: 'footerText', value: 'Shop with Faisu!! — Where every purchase feels special.', group: 'footer', label: 'Footer Text' },
      { key: 'copyrightText', value: '© 2025 Shop with Faisu!!. All rights reserved.', group: 'footer', label: 'Copyright Text' },
      { key: 'domainName', value: 'shopwithfaisu.com', group: 'general', label: 'Domain Name' },
      { key: 'metaTitle', value: 'Shop with Faisu!! | Premium Products, Beautifully Presented', group: 'seo', label: 'Meta Title' },
      { key: 'metaDescription', value: 'Discover curated collections of premium products across 20 categories. Clean design, fair prices, exceptional quality.', group: 'seo', label: 'Meta Description' },
      { key: 'heroSlides', value: '["/banners/hero-1.png","/banners/hero-2.png","/banners/hero-3.png","/banners/hero-4.png","/banners/hero-5.png"]', group: 'homepage', label: 'Hero Slides' },
      { key: 'heroSlideInterval', value: '5', group: 'homepage', label: 'Hero Slide Interval (seconds)' },
      { key: 'heroOverlayOpacity', value: '0.6', group: 'homepage', label: 'Hero Overlay Opacity' },
      { key: 'announcementBar', value: '🚚 Free shipping on orders over $75 — Shop Now!', group: 'homepage', label: 'Announcement Bar Text' },
      { key: 'announcementBarEnabled', value: 'true', group: 'homepage', label: 'Announcement Bar Enabled' },
      { key: 'navLinks', value: '[{"label":"Home","view":"home"},{"label":"Shop","view":"shop"}]', group: 'navigation', label: 'Navigation Links' },
      { key: 'heroSlideTexts', value: '[]', group: 'homepage', label: 'Hero Slide Texts' },
      { key: 'footerColumns', value: '[]', group: 'footer', label: 'Footer Columns Config' },
      { key: 'footerEnabled', value: 'true', group: 'footer', label: 'Footer Enabled' },
    ];
    await db.storeSetting.createMany({ data: settings });

    // ==================== SAMPLE ORDERS ====================
    const firstProduct = await db.product.findFirst({ where: { categoryId: electronics.id } });
    const secondProduct = await db.product.findFirst({ where: { categoryId: beauty.id } });
    if (firstProduct && secondProduct) {
      await db.order.createMany({
        data: [
          {
            orderNumber: 'SWF-0001',
            email: 'customer@example.com',
            userId: '2',
            status: 'delivered',
            total: firstProduct.price + 5.99,
            subtotal: firstProduct.price,
            shipping: 5.99,
            tax: 0,
            discount: 0,
            paymentMethod: 'card',
            paymentStatus: 'paid',
            shippingAddress: JSON.stringify({ firstName: 'John', lastName: 'Customer', phone: '+1 555-000-0001', street: '123 Main St', city: 'New York', state: 'NY', zipCode: '10001', country: 'US' }),
          },
          {
            orderNumber: 'SWF-0002',
            email: 'customer@example.com',
            userId: '2',
            status: 'shipped',
            total: secondProduct.price,
            subtotal: secondProduct.price,
            shipping: 0,
            tax: 0,
            discount: 0,
            paymentMethod: 'card',
            paymentStatus: 'paid',
            shippingAddress: JSON.stringify({ firstName: 'John', lastName: 'Customer', phone: '+1 555-000-0001', street: '123 Main St', city: 'New York', state: 'NY', zipCode: '10001', country: 'US' }),
          },
        ],
      });
    }

    const totalProducts = await db.product.count();
    const totalCategories = await db.category.count();
    const totalReviews = await db.review.count();

    return NextResponse.json({
      message: 'Database seeded successfully!',
      categories: totalCategories,
      products: totalProducts,
      reviews: totalReviews,
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Failed to seed database', details: String(error) },
      { status: 500 }
    );
  }
}